### ISSUE TITLE
Logging does not successfully use hec_ca_file for cert verification by default

### ISSUE THREAD

**Issue by ron1** [splunk/splunk-connect-for-kubernetes#127]
When running splunk-kubernetes-logging 1.1.0 on OpenShift 3.11, I encountered the following error:

```
[warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-04-11 23:31:24 +0000 chunk="234234234234" error_class=OpenSSL:SSL::SSLError error="SSL_connect returned=1 errorno=0 state=error: certificate verify failed (unable to get local issuer certificate)"
```

In order to work-around the problem, I added the following environment variable definition to the Logging fluentd-hec container in the Logging Daemonset:

```
env:
- name: SSL_CERT_FILE
  value: /fluentd/etc/splunk/hec_ca_file
```

**Comment by rockb1017** [comment]
Thank you. i have added this environment variable as another layer of ensuring ssl verification for openshift.

**Comment by sstoyanovucsd** [comment]
Hi Rock,

Adding this variable works fine for when you provide a custom certificate chain in your values.yaml (splunk.hec.caFile), but it will break the agent functionality for any installations where the Splunk server uses a certificate issued by a trusted certificate authority and the chain can be verified with the default OS CA file (/etc/pki/tls/certs/ca-bundle.crt).

What happens is that when don't provide a CA certificate file (splunk.hec.caFile), the file /fluentd/etc/splunk/hec_ca_file doesn't get created.  This results in agent's inability to verify the chain of trust of a properly issued certificate.

One can work around it by making the splunk.hec.caFile field mandatory and force people to populate it with certificate chain already present within the Docker image (at /etc/pki/tls/certs/ca-bundle.crt), but it's going to be an ugly hack.

You could extract the value of SSL_CERT_FILE  and set it according to an entry in the values.yaml (ex. splunk.hec.caFilePath) manifest, but I think it would be better to just set it to "/fluentd/etc/splunk/hec_ca_file" only if splunk.hec.caFile is set in values.yaml.

...or in pseudo-code:

```
if splunk.hec.caFile present in values.yaml
then
  set SSL_CERT_FILE=/fluentd/etc/splunk/hec_ca_file
else
  don't set SSL_CERT_FILE variable
```

If not possible to dynamically change the daemonset/deployment to leave out the SSL_CERT_FILE variable out entirely, the following would work just as well until the base image changes to one with different path to the OS-provided CA file:
```
if splunk.hec.caFile present in values.yaml
then
  set SSL_CERT_FILE=/fluentd/etc/splunk/hec_ca_file
else
  set SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt
```

**Comment by rockb1017** [comment]
Thank you for detailed explanation. we will review and see what would be the best way to handle it.

**Comment by DTTerastar** [comment]
We are seeing issues related to this as well.

**Comment by rockb1017** [comment]
with 1.4.6, you can now customize env var for logging daemonset.

**Comment by sstoyanovucsd** [comment]
Hi @rockb1017

Thank you for the quick turnaround.  There are a couple of issues with this implementation though.

1. If you leave the environment variable SSL_CERT_FILE out, as suggested by the comment in the values.yaml, it defaults to /fluentd/etc/splunk/hec_ca_file in the resulting daemonset manifest instead of leaving the variable out and defaulting to the one provided by the OS.  I can still set SSL_CERT_FILE to what I need instead of relying on the default and that works for me, but the comment is misleading.  You might want to fix the comment or change the behavior to match it.
2. The fix is good only for splunk-kubernetes-logging, but we need it for splunk-kubernetes-objects and probably splunk-kubernetes-metrics.

Thanks,
Stoyan

**Comment by rockb1017** [comment]
Thank you for the feedback. I will edit the comment and also include this for other pods for 1.4.7!

**Comment by rockb1017** [comment]
` Set SSL_CERT_FILE environment variable appropriately when using OS CA file`
is this good?

**Comment by sstoyanovucsd** [comment]
How about:

```
CA cert bundle location.  Default is "/fluentd/etc/splunk/hec_ca_file".
```

Personally I think that the default behavior when this variable is not present in the values.yaml file should be that it's not present in the respective daemonset or deployment as well.  This will lead to the daemon using the OS provided CA certs, which is more of an expected behavior than the OpenShift specific "/fluentd/etc/splunk/hec_ca_file".  OpenShift and anyone else's requirements can be accommodated by setting this variable to a custom value, which "/fluentd/etc/splunk/hec_ca_file" really is.  Defaulting to a specific use case doesn't seem like a good idea.  OpenShift is just one of plethora of Kubernetes implementations and is no more special than EKS, GKE, or vanilla Kubernetes installation.

Thanks,
Stoyan

**Comment by vinzent** [comment]
@rockb1017  as I wrote about in the PR, unsetting doesn't work. ;-) https://github.com/splunk/splunk-connect-for-kubernetes/pull/560#discussion_r578707247 

> Set SSL_CERT_FILE environment variable appropriately when using OS CA file

What is the "appropriate OS CA file"? the OS of the K8s platform is maybe not the same OS as used in the container and paths might not be the same. So a user could set it to the k8s platform OS path and then it doesnt work too. leaving room for new issues about TLS not working.

>  the OpenShift specific "/fluentd/etc/splunk/hec_ca_file"

@sstoyanovucsd  hmm... OpenShift doesn't care about your TLS config in containers. Can you explain what you mean with that this setting is specific to OpenShift? I do not see that it is related to OpenShift.

> Personally I think that the default behavior when this variable is not present in the values.yaml 

@rockb1017 I second that. But it would be a breaking change for existing users. Maybe it should only be configured if a user has set the caFile option?

**Comment by sstoyanovucsd** [comment]
@vinzent, up to version 1.4.3 the default behavior was for the agent to use whatever CA bundle is available to the OpenSSL library, which defaults to /etc/pki/tls/certs/ca-bundle.crt within the container.  Since the container image is managed by the project, no surprises can be expected and the OS of the nodes is irrelevant.  This approach worked flawlessly when agent connects to servers configured with SSL certificates issued by a trusted certificate authority.

Where OpenShift comes into play (and this may be just a special use case) is that the original issue submitter reported they had issues with self-served certificate.  This led to a code change that was intended to be a fix to ensure "ssl verification for openshift".  The problem was that this implementation broke the agent for everyone relying on non-self-signed certificates.

As I stated in my first comment, we can work around this in multiple ways, but I think that the default behavior as of 1.4.3 should be restored and custom CA bundle path should only be set when the SSL_CERT_FILE variable is defined within the values.yaml file.  As it is right now, it defaults to "/fluentd/etc/splunk/hec_ca_file", which serves a particular use case (custom certificate trust chain) and not the general user base relying on trusted certificate authorities and not setting caFile.

Probably I'm missing something, but I don't see how going back to the behavior of 1.4.3 would be a breaking change.  SSL_CERT_FILE would still be there and available for anyone wanting to use caFile and custom certificate chain.  Or maybe before the hard-coded CA path "/fluentd/etc/splunk/hec_ca_file" was only used when caFile was defined?

Anyways, although I prefer the default being as I explained, as long as the comment of the variable clearly states what one is to expect, I'm good.

Cheers!

**Comment by rockb1017** [comment]
Well noted. Thanks @vinzent @sstoyanovucsd !

I have made changes here. 
https://github.com/splunk/splunk-connect-for-kubernetes/pull/576

**Comment by sstoyanovucsd** [comment]
Thank you @rockb1017.  I'll test as soon as the changes make their way into a release and let you know how it goes.

**Comment by JonathanLachapelle** [comment]
Great timing I just found this issue this morning trying to install splunk connect on my EKS cluster.

Any idea when the release will be available?

**Comment by rockb1017** [comment]
i am waiting for internal approval for next release. hopefully next week?  ;)

**Comment by retraut** [comment]
@rockb1017 I'll wait for the fix in the next 1.4.7 version. Have the same issue here. 
Does anybody know when the next version will be released?

**Comment by rockb1017** [comment]
it is currently assigned and being reviewed. Thank you for your patience!

**Comment by sstoyanovucsd** [comment]
@rockb1017, I just tested version 1.4.7 and it works as expected.  Thank you for your time and effort you put into this project!

**Comment by rockb1017** [comment]
@sstoyanovucsd Thank you for confirming!
