### ISSUE TITLE
Add Custom Metadata / Tags

### ISSUE THREAD

**Issue by tonyswu** [splunk/splunk-connect-for-kubernetes#166]
**What would you like to be added**:

Requesting adding functionality to allow customized metadata / tags in the splunk events.

**Why is this needed**:

Currently the identifying fields include:

`pod
namespace
container_name
container_id
cluster_name
`

This is quite limited. I can think of several other useful metadata tags such as cloud account id, region, security zone, etc.

**Comment by matthewmodestino** [comment]
Hi @tonyswu!

Have you tried deploying the Splunk Connect for Kubernetes objects pod? 

```
kubectl -n splunk get pod -l release=sck-1.1.0
NAME                                                       READY     STATUS    RESTARTS   AGE
sck-1.1.0-splunk-kubernetes-logging-nmdk4                  1/1       Running   0          45s
sck-1.1.0-splunk-kubernetes-metrics-agg-5c7564bf9b-p2498   1/1       Running   0          45s
sck-1.1.0-splunk-kubernetes-metrics-rrs87                  1/1       Running   0          45s
sck-1.1.0-splunk-kubernetes-objects-5c6c9bd999-dt8hn       1/1       Running   0          45s
```

We split metadata gathering off into its own pod for finer control and to ensure optimum performance of fluentd. The objects pod lets you define what k8s objects you are interested in to pull for metadata, in this case pods would get you your labels, annotation, spec, status, etc....

The fields you mentioned in the events are meant to be "minimum viable metadata" which can then be used to do lookups in Splunk. 

It grabs all the meta you can think of on an interval and allows you to correlate it to the events in Splunk, rather than at the collector layer. 

If you still would rather do it at the collector level...technically any plugin could be used to ensure that the proper fields are added to the record before they are passed to the output plugin.

**Comment by tonyswu** [comment]
Thanks for the reply. I did modify the jq_transformer to add a few metadata of my own, was just wondering if that's something perhaps you'd be interested in adding.

I'll take a look at splunk objects as well.

**Comment by matthewmodestino** [comment]
Do you have a couple examples of what you want to add? That might help steer where we should look to add the logic.

**Comment by tonyswu** [comment]
For my use case I really just needed a few additional identifying metadata tags besides cluster_name, such as:

cloud_account_id
cloud_region

This was easy enough to do, just had to add a few lines to _helpers.tpl:

> def extract_container_info:
.........
  {{- if .Values.kubernetes.clusterName }}
  | .cluster_name = "{{ .Values.kubernetes.clusterName }}"
  {{- end }}
  {{- if .Values.custom_metadata }}
  {{-   range .Values.custom_metadata }}
  | .{{ .name }} = "{{ .value }}"
  {{-   end }}
  {{- end }}
  | .;

and configMap:

> \<fields>
.........
 {{- if .Values.custom_metadata }}
          {{-   range .Values.custom_metadata }}
          {{ .name }}
          {{-   end }}
          {{- end }}

**Comment by tonyswu** [comment]
And pass in the values like so:

> custom_metadata:
  - name: "cloud_account_id"
    value: "1234567890"
  - name: "cloud_region"
    value: "us-west-1"

**Comment by chaitanyaphalak** [comment]
@tonyswu Thats awesome, would you like to contribute the feature by filing a pull request for it. Thanks.

**Comment by sspreitzer** [comment]
Hi all, it would be cool if all available Kubernetes metadata could be enriched in a Splunk event.
See https://github.com/fabric8io/fluent-plugin-kubernetes

Most people might be interested in labels and annotations.

**Comment by chaitanyaphalak** [comment]
Thats an awesome suggestion @sspreitzer. We will look into it.

**Comment by tonyswu** [comment]
Hi @chaitanyaphalak,

Pull request https://github.com/splunk/splunk-connect-for-kubernetes/pull/203 has been created. Please review when you have a moment.

Thanks.

**Comment by chaitanyaphalak** [comment]
Closing issue, merged as part of https://github.com/splunk/splunk-connect-for-kubernetes/pull/203
