### ISSUE TITLE
Add indexer acknowledgement

### ISSUE THREAD

**Issue by sspreitzer** [splunk/splunk-connect-for-kubernetes#178]
I would like indexer acknowledgment to be added to splunk-connect.

At the moment there is no guarantee that an event gets indexed if Splunk HEC crashes.
An event can get lost if the fluentd splunk plugin successfully sends the event to Splunk HEC, but Splunk crashes or has a problem to index the event. With indexer acknowledgement an event would only be removed from fluentd buffer if the event is actually indexed.

http://dev.splunk.com/view/event-collector/SP-CAAAE8X

> By default, when HEC receives an event successfully, it immediately sends an HTTP Status 200 to the sender. However, this simply means that the event data appears valid, and the status message is sent before the event data enters the processing pipeline. During processing, there are several places where, due to an outage or a system failure, events could be lost before they are indexed. While HEC has precautions in place to prevent data loss, it's impossible to completely prevent such an occurrence, especially in the event of a hardware crash. This is where indexer acknowledgement comes in.

**Comment by chaitanyaphalak** [comment]
Hey @sspreitzer, that would be a good to have feature.

**Comment by matthewmodestino** [comment]
Indexer ack has its own challenges, even in Splunk2Splunk protocol. As long as you are aware you are trading off performance as well as increasing the chance of duplicate messages, just to avoid a scenario that may never happen (hec 200 then losing data).

This would need performance analysis against “no ack” for sure. I almost certain I have heard Splunk Arch SME’s advise agaist idx ack at scale as well...will have to double check...

**Comment by qudongfang** [comment]
Would you consider using [fluent-plugin-splunk](https://github.com/fluent/fluent-plugin-splunk/blob/master/README.hec.md) instead of [fluent-plugin-splunk-hec](https://github.com/splunk/fluent-plugin-splunk-hec) so that we can have ACK?

Another 2 relevant feature requests:

- https://github.com/fluent/fluent-bit/issues/3887
- https://github.com/splunk/fluent-plugin-splunk-hec/issues/45

**Comment by matthewmodestino** [comment]
Umm, I think you may be severely over rotating on a feature here "indexer ack" that probably causes more trouble than its worth. 

Also we purpose built fluentd-splunk-hec with way more impactful and useful featured than simply ack..

Also relying on http protocols, and buffers helps mitigate much of what indexer ack is really trying to do anyways...

**Comment by qudongfang** [comment]
Thanks for your response. I'm new to Splunk world.

I believe ACK has its pros as well as cons. Otherwise, Splunk wouldn't bother to support it. 

> probably causes more performance and data delivery issues than simply not running it

It would be great if Splunk could share some perf test results regarding `ACK vs Non-ACK`.
I couldn't find anything more concrete other than **_HEC Ack would significantly degrade performance for streaming data_** from the doc.


> what actual real world requirement is driving your ask? would love to see if we can solve it in various ways..

Let's say we have Splunk on-prem service up and running with ACK enabled by default in one of the AWS regions, AWS `eu-west-1` for an example.
And we also have services running in the Kube clusters across most of the regions from GCP, Azure, and AWS.
We'd like to have a unified solution to forward all the logs from Kube clusters running everywhere to AWS eu-west-1.

We have passed the solution of Splunk-Add-ons of the cloud provider.
I'm looking into [splunk-connect-for-kubernetes](https://github.com/splunk/splunk-connect-for-kubernetes) and [fluentbit splunk output](https://docs.fluentbit.io/manual/pipeline/outputs/splunk).

The team believes that ACK is a must until we run into the potential perf issue at the moment.

Any suggestions would be greatly appreciated!

**Comment by matthewmodestino** [comment]
"HEC Ack" and "Indexer Ack" are different things, so watch out for that bear trap! Naming is hard.

Also, if I am following you correctly, you want 1 token config to rule them all...but Splunk doesn't force you to choose one or the other, your k8s agents can opt not to implement on one token, and other service can keep doing what they want....

Splunk has solved for many things since way before k8s, so implementing something like indexer ack assumes a bunch of problems that may not reflect the reality, especially when your example goes to k8s.

When solving for k8s, the ability to send logs resiliently is actually pretty traditional...k8s node disk provide a reliable buffer to meet the most demanding customer SLAs and agent provides checkpoint and buffer/retry logic to ensure delivery. 

Are you familiar with the concept of "cobra effect"? Where your mitigation to losing logs actually makes you lose logs...its real :)

Anyways fluent-bit doesnt inplement ack afaik, and when we built this collector our eng chose not to implement, and I dont believe OTel will implement - you should take a walk through the splunk otel repo to confirm ;) 

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/splunkhecexporter


If so I recommend you look at deploying connect for k8s and watch out for our OTel updates in the future. its easier than ever! Then you can get reliable numbers you can trust. 

Otherwise holler at your Splunk account team or partner and you can ensure you solve your needs with the least pain!

**Comment by qudongfang** [comment]
> "HEC Ack" and "Indexer Ack" are different things

We're thinking about HEC ACK.

> you want 1 token config to rule them all...

We'll definitely have separate tokens for each Kube cluster.

> Are you familiar with the concept of "cobra effect"? Where your mitigation to losing logs actually makes you lose logs...its real :)

Interesting!

> Anyways fluent-bit doesnt inplement ack afaik, and when we built this collector our eng chose not to implement, and I dont believe OTel will implement - you should take a walk through the splunk otel repo to confirm ;)
> 
> https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/splunkhecexporter
> 
> If so I recommend you look at deploying connect for k8s (easier than ever) and watch out for our OTel updates in the future.
> 
> Then you can get reliable numbers you can trust and set a base line and test your needs on SLA and resilience.
> 
> Otherwise holler at your Splunk account team or partner and you can ensure you solve your needs with the least pain!

Thanks for the insights and suggestions, really appreciated it!
