### ISSUE TITLE
Differentiate stdout/stderr logs

### ISSUE THREAD

**Issue by gmichels** [splunk/splunk-connect-for-kubernetes#236]
**What would you like to be added**:
When using the logging chart, I'd like the ability to differentiate stdout to stderr.

**Why is this needed**:
Some container logs have different formats for stdout and stderr, therefore it would be useful to be able to differentiate them so they can be assigned different sourcetypes for different field extractions.

**Comment by gmichels** [comment]
I will see what I can do

**Comment by matthewmodestino** [comment]
Hi @gmichels and @chaitanyaphalak!

We chose to drop the steam id in the docker json payload because almost everyone we talked to in our field research told us that it is almost entirely useless to them because they can never be sure developers would use them accordingly. So we dropped it. 

Technically you apply the proper linebreaking and multiline formats without it....

I don't see an issue in adding it...but it will be another index time field we have to account for...and again. I question its overall value.

**Comment by chaitanyaphalak** [comment]
Its disabled by default, I think its a tradeoff the user should consider, in this case @gmichels

**Comment by gmichels** [comment]
@matthewmodestino can you clarify why this would introduce another index time field? This is simply appending the stream type to `sourcetype`.

The value to me at the moment is for some very specific containers (nginx ingress controllers), `stdout` is an access log and `stderr` is another log format. So I needed to fully differentiate them in order to parse them appropriately.

Quite honestly the true value would exist if we were able to perform the split on a per log file basis, e.g. one provides a list of container names and only those would have the stream split. However this is probably too complex to implement, at least for the benefit it may provide.

**Comment by matthewmodestino** [comment]
Apologies, I assumed you would have simply added docker's "stream" field to the event with fluentd-hec, but it looks like you are just dynamically setting the sourcetype, which should be fine, and yes, that doesn't require a different field, as you are just using an existing one - sourcetype. 

Where are you planning doing sourcetype configuration and parsing? Just be advised that because Splunk Connect for Kubernetes uses the HEC event endpoint, you will want to do line_breaking at the fluentd level. Have you tried this yet? ie. multiline (which can I assume is what is in stderr?)

Fluentd doesnt need "sourcetype" because its filters operate on "tags". You could set a concat filter like this:

```
<filter tail.containers.var.log.containers.*<container>*<pod>*.log>
  @type concat
  key log
  timeout_label @SPLUNK
  stream_identity_key stream
  multiline_start_regexp /^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}|^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}|^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\s-\s-/
  multiline_end_regexp /\\n$/
  separator ""
  flush_interval 5s
</filter>
```

Now, if you are doing Splunk side extractions and are tying to to sourcetype, then thats understandable and should work fine with the dynamic sourcetype you are making.

**Comment by gmichels** [comment]
Yes, I am doing everything I need Splunk side via props/transforms. For this particular case, stderr is not multiline, so there is no need for me to do anything else fluentd side, but I appreciate the guidance, might be useful for some other special snowflake :)

Honestly I am not a big fan of consuming container logs, I've always requested our developers to log to a true file and expose them via UFs on a DaemonSet and shared mount points. I am exploring this container log avenue for 3rd party apps that we are unable to fully control the log format/location. And during this investigation I came across the case where the format for stdout and stderr were different, so I decided to add support for this specific use case.

Anyway, feel free to close the PR if you guys feel this will not add enough value to the chart.

**Comment by chaitanyaphalak** [comment]
@gmichels This implementation is not generally in demand from the community, so we are not merging this. Thanks for all the hard work. If there is a demand for this feature we will merge it.

**Comment by asishm** [comment]
is there still no interest for this?

currently exploring various logging drivers/connectors for a big overhaul at our firm. Capturing stderr and separating is crucial for our applications. This would be a big deal-breaker for us if it is not available with Splunk.

**Comment by SSanjeevi** [comment]
we also need this feature - please reply @chaitanyaphalak  @matthewmodestino

**Comment by matthewmodestino** [comment]
If you need the stdout/stderr field, I suggest you move to our OpenTelemetry chart which with otel native log engine as it sends the stderr/stour stream and has much higher logging scale as well as many other benefits over this chart. It is the evolution path we are encouraging connect for kubernetes users to take anyways.

 https://github.com/signalfx/splunk-otel-collector-chart#splunk-opentelemetry-collector-for-kubernetes

https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/migration-from-sck.md

**Comment by SSanjeevi** [comment]
thanks for that, actually my problem i am going to try this feature, since i want logs for each item separately kind of nginx ingress logs and other items separately based on folder of logs based on pod where i have nginx, let me know if this won't work :

https://github.com/splunk/splunk-connect-for-kubernetes/issues/690#issuecomment-1017030276

you can also set the path value to focus in on specifc regex or comma separated values:

splunk-connect-for-kubernetes/helm-chart/splunk-connect-for-kubernetes/values.yaml


path: /var/log/containers/*.log 
By default we scoop up everything. With a bit of thought you could scope the path we watch down to just a specific namespace or pod by examining the path to the pod on the node and adjusting the path value as necessary....k8s puts pod_namespace_container-name-container-id in the path. So you can use that to scope down to just what you want.

https://docs.fluentd.org/input/tail#path

**Comment by matthewmodestino** [comment]
OTel allows you to do everything you can do in this chart...so I suggest moving there as your long term solution. 

It would allow you to easily create logic to dynamically set the sourcetype field based on the content of the log stream, and also lets you scope down to just what you need. 

Probably better long term support wise, regardless.
