### ISSUE TITLE
feature- add the ability to send to multiple hec endpoints & tokens

### ISSUE THREAD

**Issue by jayntguru** [splunk/splunk-connect-for-kubernetes#403]
**What would you like to be added**:

We would like the ability to send to multiple HEC endpoints and multiple HEC tokens.

Edit - this would be for logging only. Not metrics or objects.

**Why is this needed**:

We run large shared, multi tenant clusters. It would be nice to have the ability to pick a HEC configuration with a label  or in the log definition.

**Comment by matthewmodestino** [comment]
Can you please advise why this is necessary? A single token can index route ro different indexes...

Can you please provide more info?

**Comment by jayntguru** [comment]
Two entirely different Splunk infrastructure (owned by different divisions), be able to choose one index to one, one to another.

**Comment by matthewmodestino** [comment]
honestly, you are better off running 2 separate deployments. 

Otherwise please review the COPY plugin, as this already does what you are asking. But keep in mind fluentd is not an enterprise grade data broker...its a single core collector....

You should probably look into the UF and Splunk Data Stream Processor....
