### ISSUE TITLE
Fluentd Exclude Path- Question

### ISSUE THREAD

**Issue by vbottu** [splunk/splunk-connect-for-kubernetes#414]
Do we still need to exclude logs using "fluentd_exclude_path" in values.yaml if we annotate the namespace  that we don't to forward logs to splunk with "splunk,com/exclude: true"

**Comment by rockb1017** [comment]
i recommend using `fluentd_exclude_path` because it will be much more efficient. while the annotation will work well, but it will consume processing resource.

**Comment by vbottu** [comment]
We are currently setting the annotations to splunk.com/exclude=true on namespaces that we don't want logs to be forwarded to splunk. exclude_path is configured when we initially deploy SCK to exclude certain logs and as we deploy new applications exclude_path will not work anymore since the new pod is not included there, in that scenario the annotation works, but I do see that the container logs are being tailed with the annotation,not sure if it has filter to exclude them after tailing them

**Comment by rockb1017** [comment]
yea, the annotation exclusion will tail the file then filter them out. that is why using exclude_path is more efficient, but that requires restart of pods.

**Comment by vbottu** [comment]
What happens to the logs that are written in between the restart of pods. Do they get lost or get forwarded to splunk as soon as the logging pod is up?

**Comment by matthewmodestino** [comment]
can you please test the scenario you are describing? all logs get written to disk on node then read there...

**Comment by vbottu** [comment]
@matthewmodestino I have tested by adding the values under exclude_path before deploying splunk connect and after deploying when a new namespace is created and annotating with splunk.com/exclude=true , the logs of the containers from the namespace are being tailed but excluded before forwarding to splunk which is expected I believe.

**Comment by ikarlashov** [comment]
How to exclude all ns from sending logs to splunk? In our multi-tenant k8s clusters where we host multiple orgs, we don't want neither annotate NS nor configure exclude_path (it's not manageable). 

So we want to send logs only from NS annotated with  **splunk.com/index**, for example.

**Comment by matthewmodestino** [comment]
I believe our OTel collector work had implement this logic, you could look at that, or you can use the `include` path instead of `exclude` to make sure the collector only ever looks for the namespace you care about, rather than picking up all and excluding

Update your fluentd path:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/a9881ac89bfe1caa240a573be963572a20dedb55/helm-chart/splunk-connect-for-kubernetes/values.yaml#L87

OTel "include" annotation support:

https://github.com/signalfx/splunk-otel-collector-chart/blob/58ff57cf7c97e3f2ae217e15ba7a577430fc6ccc/helm-charts/splunk-otel-collector/values.yaml#L464
