### ISSUE TITLE
CPU and Memory functions limitations.

### ISSUE THREAD

**Issue by anywhere98** [splunk/splunk-connect-for-kubernetes#418]
There are some resources limits set on cpu: and memory: on “splunk-kubernetes-metrics” manifacts but not of the other. (except requests:). Is there a partially reason for that, or it can be modified base on the resources the kubernetes env. can give ?
Releated manifacts:
splunk-kubernetes-logging
splunk-kubernetes-objects

**What would you like to be added**:
Function for limiting the CPU and Memory or other resources.

**Why is this needed**:
If there is a need for CPU and Memory limits.

**Comment by gp510** [comment]
@anywhere98 - These plugins don't have the same resource requirements as metrics does. Are you running into resource issues with logging or objects?

**Comment by rockb1017** [comment]
Instead of using manifest directly in our repo, you can generate manifests yourself using `helm template` command. using helm to deploy SCK is even better! 
You can edit any daemonset or deployment yaml files to add pod's resource limits. https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
