### ISSUE TITLE
add configuration option in splunk-kubernetes-objects values.yml to specify fields to index

### ISSUE THREAD

**Issue by DrakeW** [splunk/splunk-connect-for-kubernetes#45]
Currently objects metadata are sent to Splunk in JSON format, and none of the fields are index-time fields, it imposes some difficulty to use commands like `| tstats` to get summary of data efficiently. 
One workaround we are using is by setting `INDEXED_EXTRACTION = true` in `props.conf`, but that'll eat out disk space pretty quickly considering the cardinality of the fields to index.
Therefore, it would be great if we could specify a list of fields as index-time fields in `values.yml` file.

References:
https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/manifests/splunk-kubernetes-logging/configMap.yaml#L217-L222
https://github.com/splunk/fluent-plugin-splunk-hec#fields-section-optional-single

**Comment by matthewmodestino** [comment]
Hey DrakeW!

Thanks for adding this. We have realized this in building apps internally, and I agree, that the fields should be selected with purpose, rather than indexing all with JSON`INDEXED_EXTRACTIONS. 

The workaround for now, would be to add a fluentd filter that stamps it in, similar to how we do it in he logging pod, but I agree we need to add it to the helm chart. I will try and create a sample filter to share here until we solve for this.

**Comment by chaitanyaphalak** [comment]
Merged as part of https://github.com/splunk/splunk-connect-for-kubernetes/commit/097175c71fcbb23f501b6dca238f289e77e9432d
