### ISSUE TITLE
splunk-kubernetes logging error

### ISSUE THREAD

**Issue by tannh** [splunk/splunk-connect-for-kubernetes#48]
I get meassage error
response: {"text":"No data","code":5}
Everyone help me ?

**Comment by matthewmodestino** [comment]
HI Tannh! 

what pod are you seeing that from?

**Comment by matthewmodestino** [comment]
any updates on this?

**Comment by GaryLouisStewart** [comment]
@tannh  I ran into a similar issue using (splunk enterprise v7.2.4) turns out this is due to me having enabled the '**indexer acknowledgement**' on the HEC token i setup. Oddly disabling this once my HEC token had been setup didn't solve it for me, however you could try that and redeploy the chart. 

The steps I took to resolve were as follows... 

1.  Settings => data inputs 
2.  New token
3.  Configure the settings and make sure that 'indexer acknowledgement' isn't enabled. 
4.  point your chart to use the new token

you should find that if indexer acknowledgement is enabled then it may possibly get rid of this error, however I have no guarantees that it will work in your use-case.

**Comment by dtregonning** [comment]
Thanks @GaryLouisStewart for posting your experience and your fix. @tannh if you are still having issues please reopen and reach out with more information and we will assist.
