### ISSUE TITLE
Use helm versioning properly 

### ISSUE THREAD

**Issue by holmesb** [splunk/splunk-connect-for-kubernetes#486]
> "new changes will continue to be merged to develop branch without incrementing chart version"

@rockb1017 is asserting (in issue#355 that he closed) that he is happy for enterprises to install new breaking changes even when customers don't increment the chart version.  This issue is not requesting every change to this entire repo should result in a chart version increment, just changes to the respective chart.

If Splunk Inc are breaking helm chart best practice and placing their customers at risk of introducing bugs, then this "won't fix" decision should be clearly stated.

**Comment by rockb1017** [comment]
Hello @holmesb 
Thank you for your concern. I would like to be clarify some things.

1. Every released chart will have chart version incremented. And installing released chart is how we documented for our users on README. (either through [github release artifacts](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/README.md) or using [helm repo](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/README.md)
2. Even if users are using the local clone of this git repo, as long as they use `main` branch, it doesn't violate helm chart best practices because only when it is released, it is merged to `main`. 

Was it clear?

**Comment by holmesb** [comment]
If I install chart v0.0.1, you push a bug to your helm repo, and I then helm repo update and install v0.0.1 again, I'll install your bug.  We'll just have to take it on trust that you won't "helm push" or "helm repo index" between releases.

["You can deploy a different chart with the same version as the previous one".](https://codefresh.io/docs/docs/new-helm/helm-best-practices/#chart-versus-application-versioning).  This is why it's best practice to increment the chart semver each chart change.

**Comment by rockb1017** [comment]
Updating helm repo will only be done through the release pipeline when we release. 
I will close this. if you have more feedbacks, please leave them here.
