### ISSUE TITLE
Need to set source, sourcetype to be blank

### ISSUE THREAD

**Issue by msbecker** [splunk/splunk-connect-for-kubernetes#713]
Currently using Splunk Connect for Kubernetes v1.4.5 to send logs, but not objects or metrics, to our enterprise Splunk. Requirement is that source and sourcetype need to not by set by SCK, as these are set by Splunk based on the HEC token.
For example, based on the HEC token, Splunk sets the source to something like http://cluster_dev and the sourcetype to dev:cluster
The current configuration is overwriting the source and sourcetype so in Splunk, the source is the path to the log file and the sourcetype is using the default, kube.

Need to update the configmap.yaml so the source and sourctype are left blank, so Splunk can set these. How best to do this?

**Comment by harshit-splunk** [comment]
If you don't want to collect objects and metrics at all, you can set `enabled` to false for both the plugin.

The only way I can think to stop source/sourcetype overwriting is to remove it from configMap.

To stop source/sourcetype overwriting for object, remove following lines:
- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml#L95-L99
- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml#L132-L133

To stop source/sourcetype overwriting for metrics, remove following lines:
- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml#L142-L143 
-  https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml#L134-L135

**Comment by msbecker** [comment]
Many thanks. We've already set SCK to not collect objects and metrics, so we're good there.We are collecting logs with SCK. Based on the suggested deletions, I take it we would have to do something similar to stop source/sourcetype overwriting for logs? Can you please confirm the changes we would need to make?
    On Wednesday, February 2, 2022, 08:15:46 AM EST, harshit-splunk ***@***.***> wrote:  
 
 


If you don't want to collect objects and metrics at all, you can set enabled to false for both the plugin.

The only way I can think to stop source/sourcetype overwriting is to remove it from configMap.

To stop source/sourcetype overwriting for object, remove following lines:
   
   - https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml#L95-L99
   - https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml#L132-L133

To stop source/sourcetype overwriting for metrics, remove following lines:
   
   - https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml#L142-L143
   - https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml#L134-L135

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by harshit-splunk** [comment]
Hey @msbecker, it won't be as simple to stop source/sourcetype overwriting as compared to metric and object plugin. Since logging pod has 3 different sources(pod logs, journald and non-container files) for logs, it handles sources differently. I have listed all the changes that are required below:

- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L265 (remove)
- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L306 (remove source and sourcetype)
- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L311-L320 (remove)
- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L326 (remove source and sourcetype)
- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L335 (remove sourcertype assignment)
- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L342 (remove source/sourcertype assignment)
- https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L402-L403 (remove)

**Comment by msbecker** [comment]
Many thanks. We'll test this out and see if this does it for us.

**Comment by matthewmodestino** [comment]
Hi @msbecker I think you may want to step back a bit, as the dynamic sourcetyping is there for very good reason, and setting it in the collector allows things like index routing for different workloads....

The HEC token will only allow setting a single default sourcetype, and in HEC this can still be overridden by any client setting by design, by including the index in the fields payload as described here:

https://docs.splunk.com/Documentation/Splunk/8.2.4/Data/IFXandHEC#Add_a_fields_property_at_the_top_JSON_level

What you are asking goes against much of the design and what many customers use. Perhaps a more in-depth chat about what it is you are trying to achieve would be worthwhile? Do you have a Splunk account team at your disposal?

If you simply need those specific fields, there are likely much better and more sustainable ways to achieve it. ie. setting them as "customFilter" values to create indexed fields.

**Comment by msbecker** [comment]
@matthewmodestino Unfortunately my hands are tied in this regard. The company sets the source and sourcetype for each HEC token and expects logs will be sent to Splunk without these being set by the log source. 

Our current configutation is overwriting these HEC token-set values, and we've been asked to change that.

**Comment by matthewmodestino** [comment]
@msbecker it should be clearly understood that many different types of logs from various sources/applications in the kubernetes environment, will all be lumped into one big sourcetype/source....I really recommend someone review this for its impact on usability and parsing of the data, as well as customization overhead.

**Comment by harshit-splunk** [comment]
Closing the issue as it is inactive
