### ISSUE TITLE
Better compliance with pod security standards

### ISSUE THREAD

**Issue by JesperBerggren** [splunk/splunk-connect-for-kubernetes#736]
**What would you like to be added**:
Trying to run splunk-connector-for-kubernetes in a restricted Kubernetes cluster is not really possible.
Many pod security standards are not met. See: https://kubernetes.io/docs/concepts/security/pod-security-standards/ for further details on the standards.

Running the splunk-connect-for-kubernetes (we only need logging for now) we get the following policy warnings:
**Baseline:**
- HostPath Volumes (HostPath volumes must be forbidden)

**Restricted:**
- Capabilities - (Containers must drop ALL capabilities, and are only permitted to add back the NET_BIND_SERVICE capability)
- Privilege Escalation (Privilege escalation (such as via set-user-ID or set-group-ID file mode) should not be allowed)
- Running as Non-root (Containers must be required to run as non-root users)
- Running as Non-root user (Containers must not set runAsUser to 0)
- Volume Types (The restricted policy only permits the following volume types)

I believe all the issues above can be solved for all types of clusters by doing some things differently and in a one or two cases simply reconfigure the templates to implement the policy.

Optionally it should be possible to configure it via the helm values file.

**Why is this needed**:
To live up to best practices in regards to security.

**Comment by matthewmodestino** [comment]
_`Running as Non-root (Containers must be required to run as non-root users)_

This one requires Kubernetes to allow the kubelet to write container files using non root linux group if we want to be able to pick up files as not root...Otherwise no agent will be able to satisfy not using user 0. Pretty surprising they still haven't solved for this...we should probably throw some weight in the kubernetes community around this...
